title: "10ten Design"
company:
  companyShortName: "10ten"
  companyLongName: "10ten Design And Building"
  companyAddress: "Harangvirag utca 8, Budapest, Hungary"
  companyEmail: "contact@10ten.hu"
  companyPhone: "+36 (20) 123-4567"
  companyYear: "2025"
auth:
  enabled: true
  supabaseUrl: "https://isqdkrdrbgqmtrfhqfev.supabase.co"
  supabaseKey: "sb_publishable_xprgLu5Y16svQBPseqdT_w_qmFsgaf6"
login:
  title: "Join our Community"
  providers:
    - name: "Google"
      id: "google"
      icon: "fa-brands fa-google"
      class: "btn-google"
    - name: "Facebook"
      id: "facebook"
      icon: "fa-brands fa-facebook-f"
      class: "btn-facebook"
    - name: "Apple"
      id: "apple"
      icon: "fa-brands fa-apple"
      class: "btn-apple"
